CREATE TABLE IF NOT EXISTS COMPANYS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SLOGAN VARCHAR(256),
	TEL VARCHAR(16),
	PO_BOX VARCHAR(10),
	ADDRESS VARCHAR(256),
	LOGO_URI VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS USERS (
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL UNIQUE,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	FULL_NAME VARCHAR(128),
	PASSWORD VARCHAR(512),
	USER_TYPE VARCHAR(10),
	COMPANY INT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (COMPANY) REFERENCES COMPANYS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SUBSCRIPTIONS (
	ID SERIAL PRIMARY KEY,
	DATE_OF_SUBCRIPTION TIMESTAMP NOT NULL,
	DAYS_REMAINING INT DEFAULT 0,
	DAYS_USED INT DEFAULT 0,
	TOKEN VARCHAR(512),
	SUBSCRIPTION_VALUE INT DEFAULT 0,
	SUBSCRIPTION_TYPE VARCHAR(10),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SUBSCRIBED_BY INT,
	COMPANY INT,
	FOREIGN KEY (SUBSCRIBED_BY) REFERENCES USERS (ID) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (COMPANY) REFERENCES COMPANYS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ITEMS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT,
	CREATED_BY INT,
	COMPANY INT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (COMPANY) REFERENCES COMPANYS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CAPITALS (
	ID SERIAL PRIMARY KEY,
	CURRENCY_TYPE VARCHAR(100) NOT NULL,
	CURRENCY_SYMBOL VARCHAR(100) NOT NULL,
	CREATED_BY INT,
	COMPANY INT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (COMPANY) REFERENCES COMPANYS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SUPPLIERS (
	ID SERIAL PRIMARY KEY,
	COMPANY_NAME VARCHAR(512) NOT NULL,
	CONTACT_PERSION VARCHAR(256) NOT NULL,
	CREATED_BY INT,
	COMPANY INT,
	EMAIL VARCHAR(128) NOT NULL UNIQUE,
	TEL VARCHAR(16),
	FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (COMPANY) REFERENCES COMPANYS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
	ID SERIAL PRIMARY KEY,
	FEATURE VARCHAR(512) NOT NULL,
	STATUS BOOLEAN DEFAULT FALSE,
	CREATED_BY INT,
	COMPANY INT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (COMPANY) REFERENCES COMPANYS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SALES (
	ID SERIAL PRIMARY KEY,
	RECEIPT_NO VARCHAR(32) NOT NULL,
	ITEM_BARCODE VARCHAR(32) NOT NULL,
	CREATED_BY INT,
	COMPANY INT,
	ITEM INT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (ITEM) REFERENCES ITEMS (ID) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (COMPANY) REFERENCES COMPANYS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);